{
  //Reset ROOT and connect tree file
  gROOT->Reset();
  gROOT->ProcessLine(".L ~/w/analysis/omega/scripts/rootutils.C");
  gROOT->ProcessLine(".L ~/w/analysis/omega/fid.cpp++");
  const int NTOPROC = -1; //50000000;
  const char *infile = "19013.root";
  const float R2D = TMath::RadToDeg();
  const float D2R = TMath::DegToRad();
  const float PI = TMath::Pi();
  TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject(infile);
  if (!f) {
    f = new TFile(infile); //_data/exp.root");
  }
  TDirectory *dirh10 = (TDirectory*)f->Get("h10clone");
  TDirectory *dir = (TDirectory*)f->Get("3pi-tree-recon");
  TTree *t3pi, *h10;
  dirh10->GetObject("h10",h10);
  dir->GetObject("t3pi",t3pi);
  h10->AddFriend(t3pi);

//Declaration of leaves types
   UChar_t         npart;
   UChar_t         evstat;
   UInt_t          evntid;
   Char_t          evntype;
   Int_t           evntclas;
   Float_t         q_l;
   Float_t         t_l;
   Float_t         tr_time;
   Float_t         rf_time;
   Int_t           l2bit;
   Int_t           l3bit;
   Int_t           hlsc;
   Int_t           intt;
   Int_t           gpart;
   Int_t           id[40];
   Int_t           stat[40];
   Int_t           dc[40];
   Int_t           cc[40];
   Int_t           sc[40];
   Int_t           ec[40];
   Int_t           lec[40];
   Int_t           st[40];
   Float_t         p[40];
   Float_t         m[40];
   Int_t           q[40];
   Float_t         b[40];
   Float_t         cx[40];
   Float_t         cy[40];
   Float_t         cz[40];
   Float_t         vx[40];
   Float_t         vy[40];
   Float_t         vz[40];
   Int_t           dc_part;
   Int_t           dc_sect[40];
   Int_t           dc_trk[40];
   Int_t           dc_stat[40];
   Int_t           tb_st[40];
   Float_t         dc_xsc[40];
   Float_t         dc_ysc[40];
   Float_t         dc_zsc[40];
   Float_t         dc_cxsc[40];
   Float_t         dc_cysc[40];
   Float_t         dc_czsc[40];
   Float_t         dc_vx[40];
   Float_t         dc_vy[40];
   Float_t         dc_vz[40];
   Float_t         dc_vr[40];
   Float_t         tl1_cx[40];
   Float_t         tl1_cy[40];
   Float_t         tl1_cz[40];
   Float_t         tl1_x[40];
   Float_t         tl1_y[40];
   Float_t         tl1_z[40];
   Float_t         tl1_r[40];
   Float_t         dc_c2[40];
   Int_t           ec_part;
   Int_t           ec_stat[40];
   Int_t           ec_sect[40];
   Int_t           ec_whol[40];
   Int_t           ec_inst[40];
   Int_t           ec_oust[40];
   Float_t         etot[40];
   Float_t         ec_ei[40];
   Float_t         ec_eo[40];
   Float_t         ec_t[40];
   Float_t         ec_r[40];
   Float_t         ech_x[40];
   Float_t         ech_y[40];
   Float_t         ech_z[40];
   Float_t         ec_m2[40];
   Float_t         ec_m3[40];
   Float_t         ec_m4[40];
   Float_t         ec_c2[40];
   Int_t           sc_part;
   Int_t           sc_sect[40];
   Int_t           sc_hit[40];
   Int_t           sc_pd[40];
   Int_t           sc_stat[40];
   Float_t         edep[40];
   Float_t         sc_t[40];
   Float_t         sc_r[40];
   Float_t         sc_c2[40];
   Int_t           cc_part;
   Int_t           cc_sect[40];
   Int_t           cc_hit[40];
   Int_t           cc_segm[40];
   Int_t           nphe[40];
   Float_t         cc_t[40];
   Float_t         cc_r[40];
   Float_t         cc_c2[40];
   Int_t           lac_part;
   Int_t           lec_sect[40];
   Int_t           lec_hit[40];
   Int_t           lec_stat[40];
   Float_t         lec_etot[40];
   Float_t         lec_ein[40];
   Float_t         lec_t[40];
   Float_t         lec_r[40];
   Float_t         lec_x[40];
   Float_t         lec_y[40];
   Float_t         lec_z[40];
   Float_t         lec_c2[40];
   Int_t           vidmvrt;
   Int_t           ntrmvrt;
   Float_t         xmvrt;
   Float_t         ymvrt;
   Float_t         zmvrt;
   Float_t         ch2mvrt;
   Float_t         cxxmvrt;
   Float_t         cxymvrt;
   Float_t         cxzmvrt;
   Float_t         cyymvrt;
   Float_t         cyzmvrt;
   Int_t           stamvrt;
   Int_t           mcnentr;
   UChar_t         mcnpart;
   Int_t           mcst[20];
   Int_t           mcid[20];
   Int_t           mcpid[20];
   Float_t         mctheta[20];
   Float_t         mcphi[20];
   Float_t         mcp[20];
   Float_t         mcm[20];
   Float_t         mcvx[20];
   Float_t         mcvy[20];
   Float_t         mcvz[20];
   Float_t         mctof[20];
   Int_t           nprt;
   Int_t           pidpart[20];
   Float_t         xpart[20];
   Float_t         ypart[20];
   Float_t         zpart[20];
   Float_t         epart[20];
   Float_t         pxpart[20];
   Float_t         pypart[20];
   Float_t         pzpart[20];
   Float_t         qpart[20];
   Int_t           Ipart10[20];
   Float_t         Rpart11[20];
   Float_t         Rpart12[20];
   Int_t           Ipart13[20];

   // Set branch addresses.
   h10->SetBranchAddress("npart",&npart);
   h10->SetBranchAddress("evstat",&evstat);
   h10->SetBranchAddress("evntid",&evntid);
   h10->SetBranchAddress("evntype",&evntype);
   h10->SetBranchAddress("evntclas",&evntclas);
   h10->SetBranchAddress("q_l",&q_l);
   h10->SetBranchAddress("t_l",&t_l);
   h10->SetBranchAddress("tr_time",&tr_time);
   h10->SetBranchAddress("rf_time",&rf_time);
   h10->SetBranchAddress("l2bit",&l2bit);
   h10->SetBranchAddress("l3bit",&l3bit);
   h10->SetBranchAddress("hlsc",&hlsc);
   h10->SetBranchAddress("intt",&intt);
   h10->SetBranchAddress("gpart",&gpart);
   h10->SetBranchAddress("id",id);
   h10->SetBranchAddress("stat",stat);
   h10->SetBranchAddress("dc",dc);
   h10->SetBranchAddress("cc",cc);
   h10->SetBranchAddress("sc",sc);
   h10->SetBranchAddress("ec",ec);
   h10->SetBranchAddress("lec",lec);
   h10->SetBranchAddress("st",st);
   h10->SetBranchAddress("p",p);
   h10->SetBranchAddress("m",m);
   h10->SetBranchAddress("q",q);
   h10->SetBranchAddress("b",b);
   h10->SetBranchAddress("cx",cx);
   h10->SetBranchAddress("cy",cy);
   h10->SetBranchAddress("cz",cz);
   h10->SetBranchAddress("vx",vx);
   h10->SetBranchAddress("vy",vy);
   h10->SetBranchAddress("vz",vz);
   h10->SetBranchAddress("dc_part",&dc_part);
   h10->SetBranchAddress("dc_sect",dc_sect);
   h10->SetBranchAddress("dc_trk",dc_trk);
   h10->SetBranchAddress("dc_stat",dc_stat);
   h10->SetBranchAddress("tb_st",tb_st);
   h10->SetBranchAddress("dc_xsc",dc_xsc);
   h10->SetBranchAddress("dc_ysc",dc_ysc);
   h10->SetBranchAddress("dc_zsc",dc_zsc);
   h10->SetBranchAddress("dc_cxsc",dc_cxsc);
   h10->SetBranchAddress("dc_cysc",dc_cysc);
   h10->SetBranchAddress("dc_czsc",dc_czsc);
   h10->SetBranchAddress("dc_vx",dc_vx);
   h10->SetBranchAddress("dc_vy",dc_vy);
   h10->SetBranchAddress("dc_vz",dc_vz);
   h10->SetBranchAddress("dc_vr",dc_vr);
   h10->SetBranchAddress("tl1_cx",tl1_cx);
   h10->SetBranchAddress("tl1_cy",tl1_cy);
   h10->SetBranchAddress("tl1_cz",tl1_cz);
   h10->SetBranchAddress("tl1_x",tl1_x);
   h10->SetBranchAddress("tl1_y",tl1_y);
   h10->SetBranchAddress("tl1_z",tl1_z);
   h10->SetBranchAddress("tl1_r",tl1_r);
   h10->SetBranchAddress("dc_c2",dc_c2);
   h10->SetBranchAddress("ec_part",&ec_part);
   h10->SetBranchAddress("ec_stat",ec_stat);
   h10->SetBranchAddress("ec_sect",ec_sect);
   h10->SetBranchAddress("ec_whol",ec_whol);
   h10->SetBranchAddress("ec_inst",ec_inst);
   h10->SetBranchAddress("ec_oust",ec_oust);
   h10->SetBranchAddress("etot",etot);
   h10->SetBranchAddress("ec_ei",ec_ei);
   h10->SetBranchAddress("ec_eo",ec_eo);
   h10->SetBranchAddress("ec_t",ec_t);
   h10->SetBranchAddress("ec_r",ec_r);
   h10->SetBranchAddress("ech_x",ech_x);
   h10->SetBranchAddress("ech_y",ech_y);
   h10->SetBranchAddress("ech_z",ech_z);
   h10->SetBranchAddress("ec_m2",ec_m2);
   h10->SetBranchAddress("ec_m3",ec_m3);
   h10->SetBranchAddress("ec_m4",ec_m4);
   h10->SetBranchAddress("ec_c2",ec_c2);
   h10->SetBranchAddress("sc_part",&sc_part);
   h10->SetBranchAddress("sc_sect",sc_sect);
   h10->SetBranchAddress("sc_hit",sc_hit);
   h10->SetBranchAddress("sc_pd",sc_pd);
   h10->SetBranchAddress("sc_stat",sc_stat);
   h10->SetBranchAddress("edep",edep);
   h10->SetBranchAddress("sc_t",sc_t);
   h10->SetBranchAddress("sc_r",sc_r);
   h10->SetBranchAddress("sc_c2",sc_c2);
   h10->SetBranchAddress("cc_part",&cc_part);
   h10->SetBranchAddress("cc_sect",cc_sect);
   h10->SetBranchAddress("cc_hit",cc_hit);
   h10->SetBranchAddress("cc_segm",cc_segm);
   h10->SetBranchAddress("nphe",nphe);
   h10->SetBranchAddress("cc_t",cc_t);
   h10->SetBranchAddress("cc_r",cc_r);
   h10->SetBranchAddress("cc_c2",cc_c2);
   h10->SetBranchAddress("lac_part",&lac_part);
   h10->SetBranchAddress("lec_sect",lec_sect);
   h10->SetBranchAddress("lec_hit",lec_hit);
   h10->SetBranchAddress("lec_stat",lec_stat);
   h10->SetBranchAddress("lec_etot",lec_etot);
   h10->SetBranchAddress("lec_ein",lec_ein);
   h10->SetBranchAddress("lec_t",lec_t);
   h10->SetBranchAddress("lec_r",lec_r);
   h10->SetBranchAddress("lec_x",lec_x);
   h10->SetBranchAddress("lec_y",lec_y);
   h10->SetBranchAddress("lec_z",lec_z);
   h10->SetBranchAddress("lec_c2",lec_c2);
   h10->SetBranchAddress("vidmvrt",&vidmvrt);
   h10->SetBranchAddress("ntrmvrt",&ntrmvrt);
   h10->SetBranchAddress("xmvrt",&xmvrt);
   h10->SetBranchAddress("ymvrt",&ymvrt);
   h10->SetBranchAddress("zmvrt",&zmvrt);
   h10->SetBranchAddress("ch2mvrt",&ch2mvrt);
   h10->SetBranchAddress("cxxmvrt",&cxxmvrt);
   h10->SetBranchAddress("cxymvrt",&cxymvrt);
   h10->SetBranchAddress("cxzmvrt",&cxzmvrt);
   h10->SetBranchAddress("cyymvrt",&cyymvrt);
   h10->SetBranchAddress("cyzmvrt",&cyzmvrt);
   h10->SetBranchAddress("stamvrt",&stamvrt);
   h10->SetBranchAddress("mcnentr",&mcnentr);
   h10->SetBranchAddress("mcnpart",&mcnpart);
   h10->SetBranchAddress("mcst",mcst);
   h10->SetBranchAddress("mcid",mcid);
   h10->SetBranchAddress("mcpid",mcpid);
   h10->SetBranchAddress("mctheta",mctheta);
   h10->SetBranchAddress("mcphi",mcphi);
   h10->SetBranchAddress("mcp",mcp);
   h10->SetBranchAddress("mcm",mcm);
   h10->SetBranchAddress("mcvx",mcvx);
   h10->SetBranchAddress("mcvy",mcvy);
   h10->SetBranchAddress("mcvz",mcvz);
   h10->SetBranchAddress("mctof",mctof);
   h10->SetBranchAddress("nprt",&nprt);
   h10->SetBranchAddress("pidpart",pidpart);
   h10->SetBranchAddress("xpart",xpart);
   h10->SetBranchAddress("ypart",ypart);
   h10->SetBranchAddress("zpart",zpart);
   h10->SetBranchAddress("epart",epart);
   h10->SetBranchAddress("pxpart",pxpart);
   h10->SetBranchAddress("pypart",pypart);
   h10->SetBranchAddress("pzpart",pzpart);
   h10->SetBranchAddress("qpart",qpart);
   h10->SetBranchAddress("Ipart10",Ipart10);
   h10->SetBranchAddress("Rpart11",Rpart11);
   h10->SetBranchAddress("Rpart12",Rpart12);
   h10->SetBranchAddress("Ipart13",Ipart13);

  //Declaration of leaves types
  TLorentzVector  *w4 = 0;
  TLorentzVector  *q4 = 0;
  TLorentzVector  *e0 = 0;
  TLorentzVector  *e1 = 0;
  TLorentzVector  *p0 = 0;
  TLorentzVector  *p1 = 0;
  TLorentzVector  *pip = 0;
  TLorentzVector  *pim = 0;
  TLorentzVector  *pi0 = 0;
  TLorentzVector  *omega = 0;
  TLorentzVector  *ppip = 0;
  TLorentzVector  *ppim = 0;
  TLorentzVector  *pippim = 0;
  TLorentzVector  *pippi0 = 0;
  TLorentzVector  *pimpi0 = 0;
  TLorentzVector  *mmppip = 0;
  TLorentzVector  *mmppim = 0;
  Int_t           h10idx_e;
  Int_t           h10idx_p;
  Int_t           h10idx_pip;
  Int_t           h10idx_pim;

  // Set branch addresses.
  t3pi->SetBranchAddress("w4",&w4);
  t3pi->SetBranchAddress("q4",&q4);
  t3pi->SetBranchAddress("e0",&e0);
  t3pi->SetBranchAddress("e1",&e1);
  t3pi->SetBranchAddress("p0",&p0);
  t3pi->SetBranchAddress("p1",&p1);
  t3pi->SetBranchAddress("pip",&pip);
  t3pi->SetBranchAddress("pim",&pim);
  t3pi->SetBranchAddress("pi0",&pi0);
  t3pi->SetBranchAddress("omega",&omega);
  t3pi->SetBranchAddress("ppip",&ppip);
  t3pi->SetBranchAddress("ppim",&ppim);
  t3pi->SetBranchAddress("pippim",&pippim);
  t3pi->SetBranchAddress("pippi0",&pippi0);
  t3pi->SetBranchAddress("pimpi0",&pimpi0);
  t3pi->SetBranchAddress("mmppip",&mmppip);
  t3pi->SetBranchAddress("mmppim",&mmppim);
  t3pi->SetBranchAddress("h10idx_e",&h10idx_e);
  t3pi->SetBranchAddress("h10idx_p",&h10idx_p);
  t3pi->SetBranchAddress("h10idx_pip",&h10idx_pip);
  t3pi->SetBranchAddress("h10idx_pim",&h10idx_pim);

  Long64_t nentries = NTOPROC;
  printf("NTOPROC = %lld\n",nentries);
  if (nentries<=0) nentries = h10->GetEntries();
  printf("nentries = %lld\n",nentries);
  Long64_t eventnum = 0;

  const int NPDLS = 48;
  const int NSECTS = 6;
  TH2D *h2e[NSECTS], *h2p[NSECTS], *h2pip[NSECTS], *h2pim[NSECTS];
  Fid *fid = Fid::Instance();
  TFile fout("sc_pdls_sim.root","recreate");
  for (int sidx = 0; sidx < NSECTS; sidx++) {
    TString hn = TString::Format("h_pdlVp_%s_s%d","e",sidx+1);
    TString ht = TString::Format("paddle:momentum, %s, S%d","e^{-}",sidx+1);
    h2e[sidx] = new TH2D(hn.Data(),ht.Data(),60,0,6,23,0.5,23+0.5);
    hn = TString::Format("h_pdlVp_%s_s%d","p",sidx+1);
    ht = TString::Format("paddle:momentum, %s, S%d","p",sidx+1);
    h2p[sidx] = new TH2D(hn.Data(),ht.Data(),60,0,6,NPDLS,0.5,NPDLS+0.5);
    hn = TString::Format("h_pdlVp_%s_s%d","pip",sidx+1);
    ht = TString::Format("paddle:momentum, %s, S%d","#pi^{+}",sidx+1);
    h2pip[sidx] = new TH2D(hn.Data(),ht.Data(),60,0,6,NPDLS,0.5,NPDLS+0.5);
    hn = TString::Format("h_pdlVp_%s_s%d","pim",sidx+1);
    ht = TString::Format("paddle:momentum, %s, S%d","#pi^{-}",sidx+1);
    h2pim[sidx] = new TH2D(hn.Data(),ht.Data(),60,0,6,NPDLS,0.5,NPDLS+0.5);
  }
  
  printf("created histograms\n");

  TStopwatch swmain;
  TStopwatch swgroup;
  const Int_t BLOCKSIZE = 100000;

  Long64_t nbytes = 0;
  for (Long64_t i = 0; i < nentries; i++) {
    nbytes += h10->GetEntry(i);

    if ( (++eventnum) % BLOCKSIZE == 0 ) {
      Float_t gtime = swgroup.RealTime();
      Float_t ttime = swmain.RealTime();
      Double_t percentProcessed = (((Double_t)eventnum)/(Double_t)nentries)*100;
      Float_t remaining = (100.0/percentProcessed*ttime-ttime)/60.0;
      printf("(%.2f) %lld/%.2f = %i events/sec | block = %i events/sec ... %.1f min remaining\n",percentProcessed,eventnum,ttime,((Int_t)(eventnum/ttime)),(Int_t)(BLOCKSIZE/gtime),remaining);
      swgroup.Start();
      swmain.Start(kFALSE);
    }

    if (h10idx_e==0 && h10idx_p>0 && h10idx_pip>0 && h10idx_pim>0 && w4->M()>1.6 && mmppip->M()>0.280 && mmppim->M()>0.280) {
      int ccidx = cc[0]-1;
      int scidx = sc[0]-1;
      int sector_cc = cc_sect[ccidx]-1;
      int sector_sc = sc_sect[scidx]-1;
      int scidxp = sc[h10idx_p]-1;
      int scidxpip = sc[h10idx_pip]-1;
      int scidxpim = sc[h10idx_pim]-1;
      int sect_sc_p = scidxp>=0 ? sc_sect[scidxp]-1 : -1;
      int sect_sc_pip = scidxpip>=0 ? sc_sect[scidxpip]-1 : -1;
      int sect_sc_pim = scidxpim>=0 ? sc_sect[scidxpim]-1 : -1;
      if (sector_cc == sector_sc) {// && fid->InFid(e1->P(),e1->Theta(),e1->Phi(),sector_sc+1,11)) {
	h2e[sector_sc]->Fill(e1->P(),sc_pd[scidx]);
	if (scidxp >= 0) {// && fid->InFid(p1->P(),p1->Theta(),p1->Phi(),sect_sc_p+1,2212)) {
	  h2p[sect_sc_p]->Fill(p1->P(),sc_pd[scidxp]);
	}
	if (scidxpip >= 0) {// && fid->InFid(pip->P(),pip->Theta(),pip->Phi(),sect_sc_pip+1,211)) {
	  h2pip[sect_sc_pip]->Fill(pip->P(),sc_pd[scidxpip]);
	}
	if (scidxpim >= 0) {// && fid->InFid(pim->P(),pim->Theta(),pim->Phi(),sect_sc_pim+1,-211)) {
	  h2pim[sect_sc_pim]->Fill(pim->P(),sc_pd[scidxpim]);
	}
      }
    }
  }
}
